name: Hello World Action

on:
  push:
    branches:
      - main
  workflow_dispatch:   # 允许手动触发

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build & publish
        run: |
         SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)

         node scripts/hello.js
         mv hello.txt hello-${SHORT_SHA}.txt

         git config user.name "github-actions"
         git config user.email "github-actions@github.com"

         git checkout --orphan dist
         git rm -rf .
         mv hello-${SHORT_SHA}.txt .

         git add .
         git commit -m "artifact: hello-${SHORT_SHA}.txt"
         git push -f origin dist